# This pipeline was built with many of the insights and code avalaible from this blog post:
# https://dusted.codes/github-actions-for-dotnet-core-nuget-packages

name: Build & Deploy

on:
  push:
    branches:
      - develop
      - release/*
  pull_request:
    branches:
      - develop
  release:
    types:
      - published
env:
  # Project name to pack and publish
  PROJECT_NAME: TypedId

  # GitHub Packages Feed settings
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Official NuGet Feed settings
  NUGET_FEED: https://api.nuget.org/v3/index.json
  NUGET_KEY: ${{ secrets.NUGET_KEY }}
  
  # Performance Tweaks
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
  
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack
      run: dotnet pack -v normal -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$GITHUB_RUN_ID src/$PROJECT_NAME/$PROJECT_NAME.*proj

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./src/${{ env.PROJECT_NAME }}/bin/Release/*.nupkg

    - name: Push to GitHub Feed
      run: dotnet nuget push ./nupkg/*.nupkg --source "github" --skip-duplicate --api-key GITHUB_TOKEN

  deploy:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Create NuGet package
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION="${VERSION#v}"
        dotnet pack -v normal -c Release --include-symbols --include-source -p:PackageVersion=$VERSION -o nupkg src/$PROJECT_NAME/$PROJECT_NAME.*proj
    
    - name: Push to GitHub Feed
      run: dotnet nuget push ./nupkg/*.nupkg --source "github" --skip-duplicate --api-key GITHUB_TOKEN

    - name: Push to NuGet Feed
      run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $NUGET_KEY
